import { Inter } from "next/font/google";
import "../styles/globals.css";
import Nav from "@/common/Nav";
import Header from "@/components/Header";
import { ProviderAuth } from "@/hooks/useAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderAuth>
          <div className="min-h-full">
            <Header />
            <Nav />
            <main>
              <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
                {children}
              </div>
            </main>
          </div>
        </ProviderAuth>
      </body>
    </html>
  );
}
